name: ci

on:
  push:
    branches:    
    - 'main'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: build and push to repository
        run: docker buildx build --platform linux/amd64,linux/arm/v7 --cache-from=v2nek/captcha_bot:cache --cache-to=v2nek/captcha_bot:cache -t v2nek/captcha_bot:latest --push . 
